### ISSUE TITLE
pyPTVL: Base Implementation Details

### ISSUE THREAD

**Issue by Lunatixz** [PseudoTV/PseudoTV_Manager#3]
Hey welcome to the team :) 

I'd really like to see the pyPTVL project continue... let me know if you are interested.

**Comment by xioustic** [comment]
Hey; I am interested but bogged down with work right now. I can start to try to do something in my spare time again though.

Any ideas for a roadmap? When I left off with this I had just about finished cloning the old manager's UI and started building DB functionality slowly in, but I'm not sure if that's the best approach. Maybe a list of core features to start with? I'm assuming the core purpose is channel previewing and editing.

I never actually ended up using the original manager since I built a few tools to build the m3u's myself on my desktop, and then had my Fire TV just use those without generating channels itself to reduce load. Maybe that's a feature that would be desirable for others.

**Comment by Lunatixz** [comment]
No worries, this project moves slowly anyway... It's a hobby for me :)

When you have free time contribute when you can... Thanks

We can use PTVL's chtypes as a lowkey roadmap. Out of coincidence from 0 -16 they progressively become more involved, requiring more options. If you'd like I can set up a few milestones?

Ideally the manager should allow users to create/edit channels with all the options available to PTVL along with a Kodi DB editor. Once we get something on par with the original manager... we can start expanding on the idea.

I'm not sure it's a good idea to offload m3u generation to the manager. PTVL is rather complex with its m3u building (ie. multiple aggregation rules)... If there are speed issue, I'd like to address those concerns in the PseudoTV Live itself. I believe i've reached the boundaries of file R/W performance. If I had the free time i'd like to move all channel creation from playlists to db structure. Not sure if that would increase performance... So the time and effort is a gamble.

Kevin

**Comment by xioustic** [comment]
As I come back to this: Was the c# fork ever completed (which appears to be the master branch)? Or is the VB one still the most fully feature complete? 

Previous work on pyPTVMan UI and functionality was against the VB version if I remember right. Shouldn't matter but I do need to know the current target reference.

**Comment by Lunatixz** [comment]
Honestly the VB manager for the past few years is the endeavor of a number of different developers. I'm not sure what state it's currently in.

**Comment by xioustic** [comment]
Questions (apologies if repeated, just getting work lined up):
1. What is the current manager that users use (or are referred to) today?
2. Where is the binary for that manager?
3. Where is the source code for that manager (what branch/commit specifically)?
4. What is the most up-to-date implementation (perhaps not in production)?
5. @Lunatixz: Any tips for sharing code with the base PseudoTV library (since we'll be switching to Python, it would be great to re-use modules)?
6. @Lunatixz: What manager do you use today, if any?
7. @Lunatixz: (Perhaps new issue, maybe not most appropriate for this repo) Is there a base Kodi install w/ PseudoTV that implements / could be used for quickly testing all channel types and/or settings that we'd want this manager to be able to manage?

Regarding 7: This is important for me to work on this. I actually stopped using PseudoTV Live awhile ago. I (and my family) still use Kodi on a regular basis, but my setup is a tad extreme. I have many terabytes of media on a NAS mounted via SMB, all the Kodi boxes utilize MySQL, and the boxes are all Amazon FireTVs (medium specs in the scheme of things). PsuedoTV took too long to launch and close with all my channels, which frustrated my family, and often the setup would crash after some time had passed. So we stopped using it. In addition, I never used anything outside of AutoTune.

**Comment by Lunatixz** [comment]
1. Currently no managers are up to date, So I would assume users aren't using them. All "Official" releases are abandoned.
2.  Binaries for the VB should be somewhere in this repo...
3.  Master branch has VB source
4. Master? @stereoa was the last dev working on it, @peppy6582 is very knowledgeable in the project.
5. Not sure I understand the question.
6. I don't use any mangers, I'm trying to build up the In-app manager included with PTVL. Sometimes I use notepad++ to make quick changes.
7. For quick testing, just use a clean Kodi install with my repo, use default settings and autotune channels. For quick building set your media limit to 25.

FireTV isn't a powerhouse... I have roughly 22TB over samba and a pretty hefty PTVL channel lineup... but i'm running on a HTPC's so speed and resources aren't' an issue. Your best bet is to run with minimal settings and a very low media limit. Crashes could be anything... you would have to supply a log... I don't experience crashes often, if at all.

Look at it this way a 10yr old PC would outperform the latest and greatest android device.... when it comes to running PTVL. So if PseudoTV Live is something you want to implement in your household... HTPC is the way to go. I'm trying to optimize its usage for low power devices, but user feedback is minimal. From my personal experience with a 1st gen Fire TV and a rpi 1, 2. and zero... with "Lowpower" profile enabled performance isn't great but it's usable and comparable to most epg plugins out there.

**Comment by Lunatixz** [comment]
BTW the manager with the most potential was @peppy6582 WebInterface it used Kodis built in webserver to manage PTVL.... I'd really love to see this finished but I have zero free time for this and my other projects.

**Comment by xioustic** [comment]
Regarding public releases: http://forum.kodi.tv/showthread.php?tid=206141 links to https://github.com/Lunatixz/XBMC_Addons/raw/master/zips/PTVLManager.zip so I'd assume that's the current release I'd be targeting?

Off-topic but: Would a web server / client or desktop application be more desired?
I can just as easily write JavaScript and a Python web server, but I don't think that most users will know how to set that up (access the device by IP address and port, in addition to dealing with any LAN issues). Whereas I'd assume most users can point a desktop application at a set of files quite easily.

I don't see the need for a web interface _and_ desktop application. Heck, if the channel manager inside the AddOn was quick and easy to use that'd probably be good on its lonesome, but most people within that ecosystem are using a TV remote which is less-than-ideal.

**Comment by Lunatixz** [comment]
The reason the web interface has potential and IMO is more desirable was some test code I wrote long ago to allow the EPG and other PseudoTV Live features to integrate with the browser. So looking beyond the "manager" functionality we could expand to a full feature interface which could allow users to schedule recordings, get meta,, browse epg tables, etc...
